config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :trabis
  resources :users, only: [:show, :update]

  # TODO: Add update/edit booking functionality
  resources :bookings, only: [:new, :create, :show, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  # multisearch
  include PgSearch::Model
  multisearchable against: [:start_date, :end_date]

  belongs_to :user
  belongs_to :trabi

  validates :user_id, :trabi_id, :start_date, :end_date, presence: true
  validates :rating_review, inclusion: { in: [nil, 0, 1, 2, 3, 4, 5] }
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :url, PictureUploader
  belongs_to :trabi

  validates :url, :trabi_id, presence: true
end

app/models/trabi.rb
class Trabi < ApplicationRecord
  include PgSearch::Model
  # below will accept different search-keys
  pg_search_scope :search_by_address_title_year_and_color,
    against: [:address, :title, :year, :color],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
  # below will only allow search by adress
  pg_search_scope :search_by_address,
    against: [:address],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  # multisearch
  multisearchable against: [:address, :title, :year, :color]

  belongs_to :user
  has_many :pictures
  has_many :bookings

  validates :title, :user_id, :color, presence: true
  validates :year, presence: true, inclusion: { in: (1957..1990).to_a }, numericality: { only_integer: true }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  # Nested attributes will allow us to save attributes on associated
  # records through the parent,
  # https://kolosek.com/carrierwave-upload-multiple-images/
  # accepts_nested_attributes_for :post_attachments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :photo, PictureUploader

  has_many :bookings
  has_many :trabis

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    # @trabi = Trabi.find(params[:trabi_id])
    @booking = Booking.new
    @user = User.find(params[:user_id])
    @trabi = Trabi.find(params[:trabi_id])
  end

  def create
    @user = User.find(params[:user_id])
    @trabi = Trabi.find(params[:trabi_id])
    @booking = Booking.new(booking_params)
    @booking.user = @user
    @booking.trabi = @trabi

    if @booking.save
      redirect_to(user_path(@user) + "#bookings") # TODO: update this to user profile once working
    else
      render :new
      # TODO: make an alert that says 'Dates not entered'
      #       or says "Dates invalid: already booked"
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to(user_path(@booking.user_id) + "#bookings")
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :rating_review, :content_review)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/trabis_controller.rb
class TrabisController < ApplicationController
  before_action :set_trabi, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @trabis = Trabi.search_by_address_title_year_and_color(params[:query])
      @available_trabbis = []
      if params[:start].nil?
        params_as_date = DateTime.now
      else
        params_as_date = ActiveSupport::TimeZone['UTC'].parse(params[:start])
        # filter through @trabis
        @trabis.each do |trabi|
          puts('ID')
          p trabi.id
          booked = false
          trabi.bookings.each do |booking|
            if booking.start_date == params_as_date
              booked = true
              break
              puts('TRABIS')
              p booking.start_date
              p params_as_date
            end
          end
          if booked == false
            @available_trabbis << trabi
          end
        end
        @available_trabbis.uniq!
      end
    else
      @trabis = Trabi.all
      # TODO: Show only 10 results
    end

    # GEOCODE!!!
    @trabis_geo = @trabis.geocoded
    @markers = @trabis_geo.map do |trabi|
      {
        lat: trabi.latitude,
        lng: trabi.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { trabi: trabi }),
        image_url: helpers.asset_url('map_icon.png')

      }
    end
  end

  def show
    @booking = Booking.new
    @trabi = Trabi.find(params[:id])
    @user = User.find(@trabi.user_id)
  end

  def new
    @trabi = Trabi.new
  end

  def create
    @trabi = Trabi.new(trabi_params)
      photos = params.dig(:trabi, :pictures) || []
      photos.each do |photo|
        pic = Picture.new(url: photo)
        pic.trabi_id = @trabi.id
        pic.save!
      end
    if @trabi.save
      # CALL THE create_pictures METHOD AFTER @product.save
      # create_pictures
      redirect_to trabi_path(@trabi)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @trabi.update(trabi_params)
    redirect_to trabis_path(@trabi)
  end

  def destroy
    @trabi.is_active = false
    @trabi.save!
    redirect_to trabis_path(@trabi)
  end

  private

  def create_pictures
    # photos = params.dig(:trabi, :pictures) || []
    # photos.each do |photo|
    #   pic = Picture.new(url: photo)
    #   pic.trabi_id =
    # end
  end

  def set_trabi
    @trabi = Trabi.find(params[:id])
  end

  def trabi_params
    params.require(:trabi).permit(:title, :description, :year, :color, :user_id, :address, :pictures)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def show
    @user = User.find(params[:id])

    @current_bookings = []
    @archived_bookings = []
    @trabis_info = getInfoAboutTrabi

    @user.bookings.order(start_date: :desc).each do |booking|
      (DateTime.now - booking.end_date.to_datetime).to_s
      if booking.start_date == booking.end_date
        @current_bookings << booking
      elsif booking.rating_review.nil? && (DateTime.now - booking.end_date.to_datetime) < 86_400_000
        @current_bookings << booking
      else
        @archived_bookings << booking
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if params[:file].nil?
      @user.update(first_name: params[:first_name], last_name: params[:last_name],
                   email: params[:email], phone_number: params[:phone_number],
                   street_address: params[:street_address], city_address: params[:city_address],
                   zip_address: params[:zip_address], country_address: params[:country_address])
      redirect_to user_path(@user)
    else
      @user.update(first_name: params[:first_name], last_name: params[:last_name],
                   email: params[:email], phone_number: params[:phone_number],
                   street_address: params[:street_address], city_address: params[:city_address],
                   zip_address: params[:zip_address], country_address: params[:country_address],
                   photo: params[:file]["0"])
    end
  end

  private

  def getInfoAboutTrabi
    @user = User.find(params[:id])

    result_info = {}
    @user.trabis.each do |trabi|

      now = DateTime.now
      booked = false
      upcoming_booking = now
      last_booking = now

      trabi.bookings.order(start_date: :desc).each do |booking|
        if booking.start_date <= now && now <= booking.end_date
          booked = true
        end
        if booking.start_date > upcoming_booking
          upcoming_booking = booking.start_date
        end
        if last_booking == now && booking.end_date < last_booking
          last_booking = booking.end_date
        end
      end

      result_info[trabi.id] = {
        state: booked ? "Booked" : "Free",
        upcoming: upcoming_booking == now ? "No booking" : upcoming_booking.strftime("%F"),
        last: last_booking == now ? "Never booked" : last_booking.strftime("%F")
      }

    end
    return result_info
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container">

  <div style='height: 100px;'></div>

  <div class="row justify-content-center">
    <div class="col-md-10">

      <h1 class="text-left">Create a new booking</h1>
      <hr>
      <!-- TODO: insert @trabi.title -->
      <h3> <%= @trabi.title %> </h3>

      <!-- TODO: NEED TO SORT OUT USER OWNER AND USER RENTER HERE AND CONTROLLER -->
      <div>
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <!-- TODO: insert @trabi.image1 -->
              <img class="d-block w-100" src="https://cdn.motor1.com/images/mgl/xxobp/s1/trabant-601-by-vilner.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
              <!-- TODO: insert @trabi.image2 -->
              <img class="d-block w-100" src="https://cdn.motor1.com/images/mgl/y8NPl/s1/trabant-601-by-vilner.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
              <!-- TODO: insert @trabi.image3 -->
              <img class="d-block w-100" src="https://cdn.motor1.com/images/mgl/J7X96/s1/trabant-601-by-vilner.jpg" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>

      <div class="row justify-content-around my-3">
        <div class="my-3">
          <%= form_for(@booking) do |f| %>
            <%= hidden_field_tag 'user_id', @user.id %>
            <%= hidden_field_tag 'trabi_id', @trabi.id %>
            <div class="form-group">
              <%= f.label :start_date %>
              <%= f.date_field :start_date, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :end_date %>
              <%= f.date_field :end_date, class: 'form-control' %>
            </div>
            <%= f.submit class: 'btn btn-primary' %>
          <% end %>
        </div>

        <div class="card" style="width: 24rem;">
          <div class="d-flex align-items-center">

            <!-- TODO: change user to be current_user from session -->
            <img class="rounded-circle ml-3" width="150" height=150 src=<%= @user.photo %> >
            <div class="card-body">
              <h5 class="card-title"> <strong> <%= @user.first_name %> </strong> </h5>
              <p class="card-text"> <%= @trabi.description %> </p>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TRABIDOO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Calistoga|Roboto&display=swap" rel="stylesheet">

    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
      <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div style="background-image: url('<%= image_path('background_blue.png') %>'); background-repeat: no-repeat; background-size: cover;">


  <div class="container">

    <div style="height: 120px;"></div>

    <div class="row">
      <div class="col-7">
        <%= image_tag "trabi.png", style: 'width: 600px;' %>
      </div>
      <div class="col-5">
        <div class="rounded-lg search-box d-flex flex-column justify-content-around align-items-center">
          <h1> Rent a Trabant!</h1>
          <h3> Live the history </h3>

          <div class="container search-form">
          <%= form_tag trabis_path, method: :get do %>
            <%= text_field_tag :query, params[:query], class: "searchy form-control", placeholder: "Search a Location!" %>
            <%= submit_tag "Search", class: "btn btn-primary", style: 'width: 100%;' %>
          <% end %>
          </div>

        </div>
      </div>
    </div>


    <div class="row my-3 p-3">
      <div class="col-8">
        <div class="info-box rounded-lg p-3" style="background-color:white">
          <blockquote>
            <p class="quotation"> The Running Cardboard, The Plastic Bomber, The Saxon Porsche - Just some of the many nicknames that have been given to the Trabant. Spend some time in this hilariously antiquated car - rent a Trabant! </p>
          </blockquote>
        </div>
      </div>
      <div class="d-flex justify-content-center align-items-center col-4">
        <%= image_tag 'pink.png', class: 'special-photo' %>
      </div>
    </div>

    <div class="row my-3 p-3">
      <div class="d-flex justify-content-center align-items-center p-3">
        <%= image_tag 'history.jpg', style: 'width: 100%;' %>
      </div>
    </div>


    <div class="row my-3 p-3">
      <div class="d-flex justify-content-center align-items-center col-4">
        <%= image_tag 'yellow.png', class: 'special-photo' %>
      </div>
      <div class="col-8">
        <div class="info-box rounded-lg p-3" style="background-color:white">
          <p>On November 7, 1957, the first "Trabi" rolled off the line. Thousands of them crossed from East to West Germany in 1989, two years before its production was halted. There are still some 33,000 Trabants roaming the streets of Germany today. Although there were plans for further development — and East German engineers even came up with prototypes — GDR leaders halted the production of new, enhanced models. Inevitably, the East German car industry could not keep up with the West, so the Trabi was condemned to remain the dirty, noisy exhaust blower we've known to this day. Since there was hardly any alternative to the Trabi in the GDR, it found buyers. People were even eager to wait years for it, since the demand far exceeded the supply. While around 16.4 million people lived in East Germany in 1989, only about three million Trabis were made from 1959 to 1991. 1989: The Trabi becomes the iconic 'car of the year'.The model became world famous when the Berlin Wall came down, as thousands of Trabis lined up to freely cross the border from East to West Germany in 1989, making it the "car of the year." Still, despite its charged symbolism, the Trabant disappeared from Germany's roads quickly afterwards.Western cars were sleeker, and the modern automobiles appealed to the reunited nation far more than the compact, less comfortable old-fashioned vehicle.
            <a href="https://en.wikipedia.org/wiki/Trabant">(Wikipedia)</a>
          </p>
        </div>
      </div>
    </div>

    <div class="row my-3 p-3">
      <div class="col-8">
        <div class="info-box rounded-lg p-3" style="background-color:white">
          <blockquote>
            <p class="quotation"> The Trabant was to the East what the VW Beetle was to the West - a vehicle for the masses. It was cheap to produce, with an outer body made of hard plastic. The car's moment in the spotlight came with the fall of the Berlin wall, as citizens of the DDR spilled over the newly open East-West border in their Trabis. </p>
            <footer>— Deutsche Welle</footer>
          </blockquote>
        </div>
      </div>
      <div class="d-flex justify-content-center align-items-center col-4">
        <%= image_tag 'pink.png', class: 'special-photo' %>
      </div>
    </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <div class="logo_title d-inline-flex align-items-bottom">
    <%= link_to image_tag("logo.png", :width=>100), root_path %>
    <p id="trabidoo">&nbsp Trabidoo</p>
  </div>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Rent Your Trabi", new_trabi_path, class: "nav-link", id: 'rent_trabi'%>
        </li>
        <li class="nav-item dropdown">

          <% if current_user.photo.present? %>
            <%= cl_image_tag current_user.photo, crop: :fill, gravity: :face, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "default_avatar.png", crop: :fill, gravity: :face, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>


          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
           <!--  <%= link_to "Another action", "#", class: "dropdown-item" %> -->
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>

</div>

app/views/trabis/_info_window.html.erb
<h2><%= trabi.title %></h2>

app/views/trabis/edit.html.erb
<div class="container">

  <div style='height: 100px;'></div>

  <h1>Edit: <em> <%= @trabi.title %> </em> </h1>

  <%= simple_form_for [@trabi] do |t| %>
    <%= t.input :title, label: 'Title:' %>
    <%= t.input :description, label: 'Description:' %>
    <%= t.input :year, label: 'Year:' %>
    <%= t.input :color, label: 'Color:' %>
    <%= t.input :address, label: 'Address:' %>
    <%= t.input :user_id, as: :hidden, input_html: {value: current_user[:id] } %>
    <%= t.input :pictures, label: 'Pictures:', as: :file, input_html: { multiple: true } %>
    <%= t.submit "Edit Trabant", class: "btn btn-success" %>
    <%= link_to 'cancel', trabis_path, class: "btn btn-primary"%>
  <% end %>

</div>

app/views/trabis/index.html.erb
<div style="background-image: url('<%= image_path('background_blue.png') %>'); background-repeat: no-repeat; background-size: cover;">

  <div class="container">
    <div style='height: 100px;'></div>

    <div class="d-flex">

      <div class="col-6">
        <div>
          <%= form_tag trabis_path, method: :get do %>
            <%= text_field_tag :query, params[:query], class: "form-control m-2", placeholder: "Search a Location" %>
            <%= date_field_tag :start, params[:start], class: "form-control m-2", placeholder: "From" %>
            <%= submit_tag "Search", class: "btn btn-primary m-2 w-100" %>
          <% end %>
        </div>
        <div>
          <div class="m-2">
              <div
              id="map"
              style="width: 100%;
              height: 550px;
              margin: 8px;"
              data-markers="<%= @markers.to_json %>"
              data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
              ></div>
          </div>
        </div>
      </div>

      <div class="col-6">

        <h1 class="search_results_title"> <strong> Search Results </strong> </h1>

        <div>
          <% if @available_trabbis.present? %>
            <% @available_trabbis.each do |trabi| %>
              <div class="card-product">
                <% if trabi.pictures.present? %>
                  <%= cl_image_tag trabi.pictures.first.url  %>
                <% else %>
                  <img src="https://cdn.motor1.com/images/mgl/xxobp/s1/trabant-601-by-vilner.jpg" />
                <% end %>
                <div class="card-product-infos">
                  <h2><%= link_to trabi.title, trabi_path(trabi) %></h2>
                  <p class="truncate-overflow"> <%= trabi.description[0..200] %> </p>
                </div>
              </div>
            <% end %>
          <% else %>
            <% @trabis.each do |trabi| %>
              <div class="card-product">
                <%= trabi.pictures.present? %>
                <% if trabi.pictures.present? %>
                  <%= cl_image_tag trabi.pictures.first.url  %>
                <% else %>
                  <img src="https://cdn.motor1.com/images/mgl/xxobp/s1/trabant-601-by-vilner.jpg" />
                <% end %>
                <div class="card-product-infos">
                  <h2><%= link_to trabi.title, trabi_path(trabi) %></h2>
                  <p class="truncate-overflow"> <%= trabi.description[0..200] %> </p>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/trabis/new.html.erb
<div class="container">

  <div style='height: 100px;'></div>

  <div>
    <h1>Rent out your Trabant</h1>
    <hr>
  </div>

  <!-- TODO: Prevent users from creating new trabi rentals if not logged in, make alert -->
  <div class="card p-3 rounded">
    <%= simple_form_for [@trabi] do |t| %>
      <%= t.input :title, label: 'Title:' %>
      <%= t.input :description, label: 'Description:' %>
      <%= t.input :year, label: 'Year:' %>
      <%= t.input :color, label: 'Color:' %>
      <%= t.input :address, label: 'Address:' %>
      <%= t.input :user_id, as: :hidden, input_html: {value: current_user[:id] } %>
      <%= t.input :pictures, label: 'Pictures:', as: :file, input_html: { multiple: true } %>
      <div class='d-flex justify-content-center'>
        <%= t.submit 'Submit', class: "btn btn-primary mr-4", style: "width: 200px;" %>
        <%= link_to 'Cancel', trabis_path, class: "btn btn-primary ml-4", style: "width: 200px;" %>
      </div>

    <% end %>
  </div>
</div>

app/views/trabis/show.html.erb
<div class="container">

  <div style='height: 100px;'></div>

  <div id="title">
    <h2><strong><%= @trabi.title %></strong></h2>
  </div>


  <div id="trabi-main-box">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <!-- TODO: insert @trabi.image1 -->
        <% if @trabi.pictures.present? %>
         <%= cl_image_tag(@trabi.pictures.first.url, width: 500, height:500, crop: :fill) %>
        <% else %>
          <img src="https://cdn.motor1.com/images/mgl/xxobp/s1/trabant-601-by-vilner.jpg" />
         <% end %>
      </div>
        <% if @trabi.pictures.length > 1 %>
         <% @trabi.pictures.drop(1).each do |picture| %>
             <div class="carousel-item">
        <!-- TODO: insert @trabi.image2 -->
              <%= cl_image_tag(picture.url, width: 500, height:500, crop: :fill) %>
            </div>
          <% end %>

        <% end %>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <div>
    <div id="trabi-desc-card">
      <div id="info-box">
        <p> <strong>Owner: </strong> <%= @trabi.user.email %></p>
        <p> <strong>Color: </strong> <%= @trabi.color %></p>
        <p> <strong>Year: </strong> <%= @trabi.year %></p>
        <p> <strong> Address: </strong> <%= @trabi.address %> </p>
      </div>
      <div id="desc-box">
        <p><%= @trabi.description %></p>
      </div>

    </div>
    <div id="trabi-form-card">
      <div >
        <%= form_for(@booking) do |f| %>
          <%= hidden_field_tag 'user_id', @user.id %>
          <%= hidden_field_tag 'trabi_id', @trabi.id %>
          <div class="trabi-form-group">
            <%= f.label "Date:" %>
            <%= f.date_field :start_date %>
            <%= f.submit class: 'trabi-btn', value: 'Book this Trabant', id: "rent-btn" %>
          </div>

        <% end %>
      </div>
    </div>
    <div id="trabi-btn-card">
      <%= link_to 'Edit Trabant', edit_trabi_path, class: "trabi-btn"%>
      <%= link_to 'Back to Search', trabis_path, class: "trabi-btn"%>
      <%= link_to "Delete", trabi_path(@trabi), class: "trabi-btn",
               method: :delete,
               data: { confirm: "Are you sure?" } %>
    </div>
  </div>




</div>



<hr>
  <div id="title">
    <h4><strong>Reviews</strong></h4>
  </div>
  <% if @trabi.bookings.length > 0 %>
    <% @trabi.bookings.each do |booking| %>
      <% if booking.rating_review != nil %>
      <div id="trabi-review-card">

            <p><strong>Rating:</strong>
            <% if booking.rating_review.zero? %>
                <i id="skull" class="fas fa-skull-crossbones trabi-icon-skull"></i>
            <% else %>
                <% booking.rating_review.times do %>
                  <i id="star" class="fas fa-star trabi-icon-star"></i>
                <% end %>
              </a>
            <% end %>
            <div id="rating-line">
            <p id="user"><strong>User: </strong><%= booking.user.email %></p>
            <p><strong>Date: </strong><%= booking.start_date.strftime("%F") %></p>
          </div>
        <div id="review-line">
          <p><%= booking.content_review %></p>
        </div>
      </div>
      <% end %>
    <% end %>
  <% else %>
    <p><em>No reviews yet</em></p>
  <% end %>